name: quizzer

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quizzer-frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_API_BASE_URL=http://localhost:5000/api
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
